### ISSUE TITLE
Scraper to scrape information and push to an easily consumable file in git

### ISSUE THREAD

**Issue by xlanor** [Ukraine-Relief-Efforts/ukraine-info-guide#1]
To reduce complexity, I suggested previously in discord that we should avoid a backend component (for now), and instead rely as much as possible on github infrastructure to get the project going.

As such, I was thinking that for the information (border crossings/reception points) that we are looking at, we could scrape them on a 15 minute interval and push them as git commits to a git repository that the frontend would then pull from.

**Comment by xlanor** [comment]
https://www.gov.pl/web/udsc/ukraina-en
https://www.gov.pl/web/udsc/ukraina2

**Comment by EchoRuby68** [comment]
Moldova border crossing info:
https://www.border.gov.md/index.php/informare

**Comment by Oulsen** [comment]
@xlanor Can we close this because you guys created a new repo just for the scraper?

**Comment by xlanor** [comment]
Yes go ahead
