### ISSUE TITLE
Crypto donation button

### ISSUE THREAD

**Issue by oetherington** [Ukraine-Relief-Efforts/ukraine-info-guide#146]
https://www.ukrainenow.org/ has a button to donate cryptocurrency to help Ukraine.

https://www.defendukraine.org/donate also has crypto addresses for donating directly to the Ukrainian government.

We should add some ability to the site to make a direct crypto donation.

This is a low priority issue for after the MVP is released.

**Comment by ErmannoOliveri** [comment]
Hi, can I work on the issue?

**Comment by oetherington** [comment]
I think it's best to leave this one for now as it's probably going to end up being on a different website - I'll make another comment on this ticket when we know for certain.

**Comment by ErmannoOliveri** [comment]
Ok, Thanks

**Comment by nbaldy** [comment]
If this isn't available for new people, can we close it for now? I think keeping issues synced with what's in-progress or we want new people working on could be important to getting new hands on deck
