### ISSUE TITLE
Wrapping text in Italian translation

### ISSUE THREAD

**Issue by Jystro** [Ukraine-Relief-Efforts/ukraine-info-guide#156]
The text for "Border crossing" in Italian wraps over two lines, making it less readable.
I've provided a shorter translation with #155 , but that didn't solve the problem. 

![image](https://user-images.githubusercontent.com/35638179/156387971-9c1b1042-6810-4656-b0ec-da907a2b7cad.png)

**Comment by creadicted** [comment]
Can be closed
