### ISSUE TITLE
"Retrieved at" data does not render with some translations 

### ISSUE THREAD

**Issue by plotka** [Ukraine-Relief-Efforts/ukraine-info-guide#194]
Doesn't work with Russian (Русский) and Serbian (Српски)

![Screenshot 2022-03-05 at 18 40 44](https://user-images.githubusercontent.com/6666010/156894267-609072f1-e935-4ec1-8e49-6db811601985.png)

**Comment by creadicted** [comment]
@plotka works for me. Can you check it again?

**Comment by plotka** [comment]
Yeah seems to work now.
