### ISSUE TITLE
Sync API

### ISSUE THREAD

**Issue by kramduckner** [Ukraine-Relief-Efforts/ukraine-info-guide#26]

**Comment by kramduckner** [comment]
Since we're using redux toolkit, might be a good idea to use the async thunks https://redux-toolkit.js.org/api/createAsyncThunk that come with the library.

**Comment by Seth-McKilla** [comment]
Just throwing this out there but instead of going the redux path with thunk, we could use a much less verbose and seamless integration with NextJS using stale while revalidate hook (https://swr.vercel.app/)

**Comment by kramduckner** [comment]
How will these solutions work with our redux state? I'm game for whatever, just don't want a bunch of different patterns in there and want to make sure we're not negating any of the benefits of using redux!

**Comment by kramduckner** [comment]
Just saw that you we're possibly migrating to next.js? If that's happening, I say do whatevers best practice within that context.

**Comment by plotka** [comment]
I also think react-query would work well if we don't switch to nextjs. If we do switch, I agree with @kramduckner but I am not very familiar with the best practices. Also, I don't mind removing the redux logic altogether as I think useState and Context API should suffice.

**Comment by StigAkl** [comment]
I agree about removing the redux logic. Imo it might be a bit overkill and can potensially slow down the development process as less developers are comfortable with it. The priority should be to get the most important information out as fast as possible. 
If needed we can probably spend some time re-implementing it after we've got the most important parts to production.
