### ISSUE TITLE
OSM Geolocation implementation

### ISSUE THREAD

**Issue by elecarno** [Ukraine-Relief-Efforts/ukraine-info-guide#86]
major note: must ask for user permission

**Comment by nbaldy** [comment]
Hey, I was just wondering how this was going and if you wanted any help with this - I'm working on bringing some new people on board looking for things to do! Let me know if you want me to point them to you to assist!

**Comment by nbaldy** [comment]
Sounds good - I'll see if we can get another set of eyes on this - not to take over but to lend assistance where we can. Thank you!

**Comment by elecarno** [comment]
Got it sorted 👍
