### ISSUE TITLE
Replace react-select

### ISSUE THREAD

**Issue by oetherington** [Ukraine-Relief-Efforts/ukraine-info-guide#87]
We currently use react-select for the LanguagePicker (and nothing else).

It's a great library, but it takes up about 60kb in our js bundle (thanks to its dependency on memoize-one and some @emotion libraries), which is way more than we can justify for a dropdown menu that's only used in one place.

The goal of this ticket is to remove react-select and to either replace it with a smaller library, or to simply implement a nice dropdown ourselves to use here.

It doesn't need the complex text search functionality that react-select has, but it should look like a clean, coherent part of the page.

**Comment by plotka** [comment]
Good idea, I did a quick search and found this one - [react-select-search](https://www.npmjs.com/package/react-select-search) it's 3.2KB minzipped, what do you think?

**Comment by oetherington** [comment]
@plotka That looks perfect to me!
